// Generated by Maps Plugin for Boilerplate <?php echo VERSION; ?>

document.addEventListener( 'DOMContentLoaded', function() {

    var maps = <?php echo json_encode( get('site.maps') ); ?>;

    for (var id in maps) {

        // Check Property is a Map
        if (!maps.hasOwnProperty(id)) {
            continue;
        }

        // Define ID
        maps[id].id = id;

        // Create map instance
        maps[id].instance = new google.maps.Map(document.getElementById('map-' + maps[id].id), {
            center: {
                lat: parseFloat(maps[id].destination.lat),
                lng: parseFloat(maps[id].destination.lng)
            },
            draggable: maps[id].config.draggable,
            scrollwheel: maps[id].config.scrollwheel,
            zoom: maps[id].config.zoom
        });

        <?php if ( get('site.env') == 'dev' ): ?>console.log(maps[id]);<?php endif; ?>

    }

} );
